name: myntra_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/myntra.png
    - assets/images/drawer/drawer-header.webp
    - assets/images/home/kids.jpg
    - assets/images/home/men.jpg
    - assets/images/home/women.jpg
    - assets/images/home/footwear.jpg
    - assets/images/home/accessories.jpg
    - assets/images/home/jewellery.jpg
    - assets/images/home/beauty.jpg
    - assets/images/drawer/drawer-footer.webp
    - assets/images/home/offer.webp
    - assets/images/login/login.webp
    - assets/images/login/login2.png